version: '3.4'
services:
  app:
    build:
      context: ./app
    environment:
      - 'DATABASE_URL=mysql://root:root@db:3306/test'
    depends_on:
      - db
    volumes:
      - './app:/var/www/html:rw,cached'
    ports:
      - target: 80
        published: 8020
        protocol: tcp
  db:
    image: 'mysql:5.7'
    environment:
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - './db:/var/lib/mysql:rw'
    ports:
      - target: 3306
        published: 3310
        protocol: tcp
